### ISSUE TITLE
Make it fast!

### ISSUE THREAD

**Issue by danger89** [servo/rust-cssparser#164]
As stated in the [readme](https://github.com/servo/rust-cssparser/#todo), this is still an open item.

So I created an issue, to higher the importance and make CSS parsing faster in servo. I think at some point you need to focus on code quality, maintenance and performance, instead of (mainly) adding new features.

But as always, keep up the good work.

Regards,
Melroy

**Comment by SimonSapin** [comment]
Thanks for pointing this out. This section of README is 4 years old, and largely obsolete. I’ve removed it.

“Mainly adding new features” is not representative at all of what’s been happening in cssparser. If fact the feature set grew little since the initial implementation. Most changes have been correctness fixes and, yes, performance improvements. Some of those are #66, #102, #110, #112, #118, #122, #124, #132, #157, #159; and we have more planned. CSS parsing performance is one of the focuses of [Stylo](https://wiki.mozilla.org/Quantum/Stylo), which brings this code into Firefox.

**Comment by danger89** [comment]
Ah great. Good job.
