### ISSUE TITLE
Future compat warning

### ISSUE THREAD

**Issue by est31** [servo/rust-cssparser#254]
Currently, there is a future compat warning firing when building the codebase:

````
warning: cannot specify lifetime arguments explicitly if late bound lifetime parameters are present
   --> src/rules_and_declarations.rs:537:30
    |
537 |         parse_until_before::<'i, 't, _, _, _>(input, Delimiter::CurlyBracketBlock, |input| {
    |                              ^^
    | 
   ::: src/parser.rs:959:13
    |
959 |     parser: &mut Parser<'i, 't>,
    |             - the late bound lifetime parameter is introduced here
    |
    = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
    = note: for more information, see issue #42868 <https://github.com/rust-lang/rust/issues/42868>
````

**Comment by SimonSapin** [comment]
Yes, I am unhappy about this warning.

The diagnostic is not clear at all, and even after much discussion in https://github.com/rust-lang/rust/issues/42868 and on IRC I’m not sure what it means. None of the possible fixes suggested by various people are accepted by the compiler for this code.

So we’re stuck with an obscure warning we can’t silence and that no-one knows how to fix.

**Comment by lqd** [comment]
For documentation purposes, here's a summary of the situation:
- there are currently 4 instances of code designed to avoid rustc bug https://github.com/rust-lang/rust/issues/42508 about region inference and implied bounds in closures: [#1](https://github.com/servo/rust-cssparser/blob/master/src/rules_and_declarations.rs#L284-L292), [#2](https://github.com/servo/rust-cssparser/blob/master/src/rules_and_declarations.rs#L486-L489), [#3](https://github.com/servo/rust-cssparser/blob/master/src/rules_and_declarations.rs#L535-L539), [#4](https://github.com/servo/rust-cssparser/blob/master/src/rules_and_declarations.rs#L544-L547).
- these 4 occurrences, in turn, now trigger the `late_bound_lifetime_arguments` lint tracked in https://github.com/rust-lang/rust/issues/42868, because of the lifetime annotations to both early and late-bound lifetimes for the generic `parse_*` function calls.
- in #260 I was able to avoid both of these by lifting the closure argument to a variable which can be removed in the future, and mentioned this issue in FIXME comments for more information. (Incidentally, 2 scopes also had to be added to make it work on 1.31.0, but are not technically required with more recent stable releases: they could removed if the minimum rust version were to be raised, for example to 1.36.0)

When the rustc bug is fixed, these `callback` variables can be removed by inlining them as arguments to these 4 function calls (and the type annotation on the closure parameter will also become unnecessary).
