### ISSUE TITLE
No way to tell if nested block closed by delimiter or EOF

### ISSUE THREAD

**Issue by luniv** [servo/rust-cssparser#69]
I'm working on parsing media queries, and my understanding is that the syntax specifies that a media feature must end with a `)` [1]. 

For example, if you have the string **"(width"**, `Parser::parse_nested_block` will return `Ok(_)`. And there is no easy way to determine how if it was closed by a `)` or EOF, as far as I can see.

```rust
#[test]
fn block_closed_by_delimiter() {
    let mut input = Parser::new("(width");

    assert!(input.expect_parenthesis_block().is_ok());
    let result = input.parse_nested_block(|input| {
        assert!(input.expect_ident_matching("width").is_ok());
        assert!(input.is_exhausted());
        Ok(true)
    });
    assert!(result.is_err());
}
```
1: http://drafts.csswg.org/mediaqueries/#typedef-media-feature
 > `<media-feature> = ( [ <mf-plain> | <mf-boolean> | <mf-range> ] )`

**Comment by SimonSapin** [comment]
This is by design. The [CSS error handling rules](http://dev.w3.org/csswg/css2/syndata.html#unexpected-eof) say that blocks close implicitly at EOF. (The newer [CSS Syntax](http://dev.w3.org/csswg/css-syntax/) spec has [the same behavior](http://dev.w3.org/csswg/css-syntax/#consume-simple-block), but is less explicit about it.) This rule is implicit in all other grammar-like syntax definitions, to reduce verbosity.

By the way, you might want to copy some of Servo’s [`media_queries.rs`](https://github.com/servo/servo/blob/master/components/style/media_queries.rs). Maybe eventually the parsing parts could be move to rust-cssparser.

**Comment by luniv** [comment]
Ah. Thanks for the information!

I admit the reason I filed this bug was because I was extending the media query support in Servo (kind of got away on me; have pretty much the full spec implemented, just testing it now)
